#!/bin/bash

set -e

dotenv () {
  set -a
  [ -f .env ] && . .env
  set +a
}

dotenv

#########################
# create a local .npmrc #
#########################
if ! [ -f .npmrc ]; then
  if [ -n "${NPM_TOKEN}" ]; then
    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  fi

  echo "@instructure:registry=https://registry.npmjs.org/" >> .npmrc

  if [ -n "${NPM_EMAIL}" ]; then
    echo "email=${NPM_EMAIL}" >> .npmrc
  fi

  if [ -n "${NPM_USERNAME}" ]; then
    echo "name=${NPM_USERNAME}" >> .npmrc
  fi
fi

cat .npmrc

########################
# set local git config #
########################
if [ -z "$(git config remote.origin.url)" ]; then
  if [ -n "${GH_REMOTE}" ]; then
    git remote add origin ${GH_REMOTE}
  fi
fi

if [ -n "${GH_EMAIL}" ]; then
  git config user.email "${GH_EMAIL}"
fi

if [ -n "${GH_USERNAME}" ]; then
  git config user.name "${GH_USERNAME}"
fi

git config push.default simple

echo "git remote -v"
git remote -v
git config user.email
git config user.name
git config push.default
