#!/bin/bash -e

babel=$MODULES_PATH/.bin/babel
webpack=$MODULES_PATH/.bin/webpack

rm -rf $BUILD_PATH

$BASE_PATH/tasks/transpile
$BASE_PATH/tasks/dist

# Copy package
cp README.md $BUILD_PATH/
cp .npmignore $BUILD_PATH/
cp LICENSE $BUILD_PATH/
node -p 'p=require("./package");p.scripts=p.devDependencies=undefined;JSON.stringify(p,null,2)' > $BUILD_PATH/package.json
