#!/bin/bash -e

function program_is_installed {
  # set to 1 initially
  local return_=1
  # set to 0 if not found
  type $1 >/dev/null 2>&1 || { local return_=0; }
  # return value
  echo "$return_"
}

if [ ! $(program_is_installed nvm) ]
  then
    echo "-- install nvm...";
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
fi

echo "-- install node"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm install && nvm use

