#!/bin/bash -e

# make sure working directory is clean
if [ ! -z "$(git status --porcelain)" ]; then
  echo Refusing to operate on unclean working directory
  echo Use \"git status\" to see which files have been modified
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
DOCS_PATH=$BUILD_PATH/docs

printf "Enter commit SHA to deploy to gh-pages: "
read commit

git fetch origin

git checkout $commit

if [ "`git branch --list gh-pages`" ]; then
  git branch -D gh-pages
fi

# build docs
$BASE_PATH/tasks/docs

git checkout --orphan gh-pages

# remove superfluous files
git reset .
git clean --force -d --exclude $DOCS_PATH
rm -rf node_modules
find . -type f | egrep -v ".git/|$DOCS_PATH/" | xargs rm
find . -type d -empty -delete

mv $DOCS_PATH/* .
git clean --force -d $BUILD_PATH
git add .
git commit -m "Update gh-pages"

git push -f origin gh-pages:gh-pages

git commit -m "Rebuild pages" --allow-empty

git push origin gh-pages:gh-pages

git checkout $BRANCH

# restore node modules
npm install
