#!/bin/bash -e

# make sure working directory is clean
if [ ! -z "$(git status --porcelain)" ]; then
  echo Refusing to operate on unclean working directory
  echo Use \"git status\" to see which files have been modified
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
DOCS_PATH=$BUILD_PATH/docs

git fetch origin

git checkout origin/latest

npm install

# build docs
$BASE_PATH/tasks/docs

# delete the local gh-pages branch
if [ "`git branch --list gh-pages`" ]; then
  git branch -D gh-pages
fi

git checkout --orphan gh-pages
git pull origin gh-pages

# remove superfluous files
git reset .
git add .gitignore
git clean --force -d

mv -f $DOCS_PATH/* .
git add .
git commit -m "Update gh-pages for `git log origin/latest -1 --pretty="%H"`"

git push origin gh-pages:gh-pages

git checkout $BRANCH

# restore node modules
npm install
