#!/bin/bash -e

# make sure working directory is clean
if [ ! -z "$(git status --porcelain)" ]; then
  echo Refusing to operate on unclean working directory
  echo Use \"git status\" to see which files have been modified
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)

printf "Enter commit SHA to release: "
read commit_sha

git fetch origin

git checkout $commit_sha

package_version=$(node -p "require('./package').version")

release_tag="v$package_version"

$BASE_PATH/tasks/test --single-run
$BASE_PATH/tasks/build
$BASE_PATH/tasks/docs

git tag -am "Version $package_version" $release_tag

git push origin $release_tag
git push origin $commit_sha:latest

npm publish

git checkout $BRANCH
