#!/bin/bash -e

# make sure working directory is clean
if [ ! -z "$(git status --porcelain)" ]; then
  echo Refusing to operate on unclean working directory
  echo Use \"git status\" to see which files have been modified
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)

git checkout origin/master

package_version=$(node -p "require('./package').version")

release_tag="v$package_version"

$BASE_PATH/tasks/test --single-run
$BASE_PATH/tasks/build
$BASE_PATH/tasks/docs

git tag -am "Version $package_version" $release_tag
git tag -am "Latest" latest -f

git push origin $release_tag
git push origin latest -f

npm publish

git checkout $BRANCH
