/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 - present Instructure, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Fetches version data from versions.json
 * Returns null or an object:
 * {
 *   latestVersion: string, (e.g.: 'v8')
 *   previousVersions: string[] (e.g.: ['v7', 'v6'])
 * }
 * @param signal {AbortController.signal}
 * @returns {Promise<null|object>}
 */
const fetchVersionData = async (signal: AbortSignal) => {
  const isLocalHost = window.location.hostname === 'localhost'
  if (!isLocalHost) {
    try {
      const isGhPages =
        window.location.origin === 'https://instructure.github.io'
      const versionsDataUrl =
        window.location.origin +
        (isGhPages ? '/instructure-ui' : '') +
        '/versions.json'
      const result = await fetch(versionsDataUrl, { signal })
      if (!result.ok) {
        return undefined
      }
      return await result.json()
    } catch {
      return undefined
    }
  }
  return undefined
}

type MinorVersionData = {
  libraryVersions: string[]
  defaultVersion: string
}

/**
 * Fetches minor version data from docs-versions.json.
 * This file is generated by the docs build and describes which
 * library minor versions are available (e.g. v11_5, v11_6).
 */
const fetchMinorVersionData = async (
  signal: AbortSignal
): Promise<MinorVersionData | undefined> => {
  try {
    const result = await fetch('docs-versions.json', { signal })
    if (!result.ok) {
      return undefined
    }
    const data = await result.json()
    return {
      libraryVersions: data.libraryVersions,
      defaultVersion: data.defaultVersion
    }
  } catch {
    return undefined
  }
}

/**
 * if we are on the docs page of a legacy version,
 * the path includes the version number, e.g. `/v7` or `/v8`
 */
const versionMatch = window.location.pathname.match(/\/(v\d+)(\/|$)/)
const versionInPath = versionMatch ? versionMatch[1] : null

export default fetchVersionData
export { fetchVersionData, fetchMinorVersionData, versionInPath }
export type { MinorVersionData }
