FROM instructure/node:8.6

USER root

# Add Chrome
RUN curl --silent "https://dl-ssl.google.com/linux/linux_signing_key.pub" | apt-key add - \
 && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > "/etc/apt/sources.list.d/google.list" \
 && apt-get update --quiet=2 \
 && apt-get install libgconf-2-4 --quiet=2 \
 && apt-get install --quiet=2 google-chrome-beta > /dev/null \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Add source and install dependencies
RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/

COPY ./package.json /usr/src/app/
COPY ./yarn.lock /usr/src/app
COPY .yarnrc /usr/src/app

RUN yarn --ignore-scripts --pure-lockfile --no-progress
COPY . /usr/src/app/

RUN chown -R docker:docker /usr/src/app
USER docker
