FROM instructure/node:8

USER root

ENV APP_HOME /usr/src/app

RUN mkdir -p $APP_HOME/coverage
RUN chown -R docker:docker $APP_HOME

VOLUME $APP_HOME/coverage

# keep running so we can copy over the coverage reports
ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
