#!/bin/bash

set -e

env_file=.env.test

dotenv () {
  set -a
  [ -f .env ] && . .env
  set +a
}

dotenv

function cleanup() {
  exit_code=$?
  set +e

  echo "Copying coverage reports..."
  docker cp $(docker-compose ps -q coverage):/usr/src/app/coverage .

  echo "Cleaning up..."
  docker-compose stop test
  docker-compose rm -f test
  docker rmi -f $(docker images -qf "dangling=true") &>/dev/null

  rm $env_file

  exit $exit_code
}

trap cleanup INT TERM EXIT

export COMPOSE_FILE=./docker-compose.test.yml

echo "Creating ${env_file} file..."
(
cat << EOF
CI=true
NPM_TOKEN=${NPM_TOKEN}
NPM_USERNAME=${NPM_USERNAME}
NPM_EMAIL=${NPM_EMAIL}
GIT_EMAIL=${GIT_EMAIL}
GIT_USERNAME=${GIT_USERNAME}
GIT_REMOTE_URL=${GIT_REMOTE_URL}
GIT_REMOTE_NAME=${GIT_REMOTE_NAME}
JIRA_CONSUMER_KEY=${JIRA_CONSUMER_KEY}
JIRA_TOKEN=${JIRA_TOKEN}
JIRA_SECRET=${JIRA_SECRET}
JIRA_PEM_PATH=/home/docker/.ssh/gerritbot_jira.pem
SLACK_USERNAME=${SLACK_USERNAME}
SLACK_WEBHOOK=${SLACK_WEBHOOK}
SSH_KEY_PATH=${SSH_KEY_PATH}
NODE_VERSION_LOCKED=${NODE_VERSION_LOCKED}
SSH_USERNAME=${SSH_USERNAME}
UV_THREADPOOL_SIZE=128
EOF
) > $env_file

echo "Pulling image..."
docker-compose pull

echo "Building services..."
docker-compose build

echo "Preparing container..."
container=$(docker-compose run -d --rm test tail -f /dev/null)

if [[ -e "${SSH_KEY_PATH}" ]]; then
  echo $SSH_KEY_PATH
  docker exec -u 0 $container mkdir /home/docker/.ssh
  docker exec -u 0 $container chown -R docker:docker /home/docker/.ssh
  docker cp "$SSH_KEY_PATH" $container:/home/docker/.ssh/
else
  echo "SSH_KEY_PATH not set on post merge build"
  echo "Please set SSH_KEY_PATH or set CI to false"
  exit 1
fi

if [[ -e "${JIRA_PEM_PATH}" ]]; then
  docker cp "${JIRA_PEM_PATH}" $container:/home/docker/.ssh/gerritbot_jira.pem
fi

docker cp .git $container:/usr/src/app/.git
docker exec -u 0 $container chown -R docker:docker /usr/src/app/.git
docker exec -u 0 $container chown -R docker:docker /home/docker/.ssh

echo "Running release..."
docker exec $container bash -c "ssh-keyscan -p 29418 gerrit.instructure.com >> ~/.ssh/known_hosts"
docker exec $container bash -c "GIT_SSH_COMMAND='ssh -i /home/docker/.ssh/ssh-key-SSH_KEY_PATH -l "\$SSH_USERNAME"' yarn release"

docker stop $container
