#!/bin/bash

set -e

env_file=.env.test

dotenv () {
  set -a
  [ -f .env ] && . .env
  set +a
}

dotenv

function cleanup() {
  exit_code=$?
  set +e

  echo "Copying coverage reports..."
  docker cp $(docker-compose ps -q coverage):/usr/src/app/coverage .

  echo "Cleaning up..."
  docker-compose stop test
  docker-compose rm -f test
  docker rmi -f $(docker images -qf "dangling=true") &>/dev/null
  rm $env_file

  exit $exit_code
}

trap cleanup INT TERM EXIT

export COMPOSE_FILE=./docker-compose.test.yml

echo "Creating ${env_file} file..."

(
cat << EOF
POST_MERGE_BUILD=${POST_MERGE_BUILD}
NPM_TOKEN=${NPM_TOKEN}
NPM_USERNAME=${NPM_USERNAME}
NPM_EMAIL=${NPM_EMAIL}
NPM_SCOPE=${NPM_SCOPE}
GIT_REMOTE=${GIT_REMOTE}
GIT_EMAIL=${GIT_EMAIL}
GIT_USERNAME=${GIT_USERNAME}
GH_PAGES_DIR=${GH_PAGES_DIR}
GH_PAGES_BRANCH=${GH_PAGES_BRANCH}
GH_PAGES_REPO=${GH_PAGES_REPO}
GH_PAGES_CNAME=${GH_PAGES_CNAME}
JIRA_HOST=${JIRA_HOST}
JIRA_CONSUMER_KEY=${JIRA_CONSUMER_KEY}
JIRA_TOKEN=${JIRA_TOKEN}
JIRA_SECRET=${JIRA_SECRET}
JIRA_PEM=/home/docker/.ssh/gerritbot_jira.pem
JIRA_PROJECT_ID=${JIRA_PROJECT_ID}
JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
SLACK_USERNAME=${SLACK_USERNAME}
SLACK_CHANNEL=${SLACK_CHANNEL}
SLACK_EMOJI=${SLACK_EMOJI}
SLACK_WEBHOOK=${SLACK_WEBHOOK}
CHANGELOG_URL=${CHANGELOG_URL}
CI=true
EOF
) > $env_file

echo "Pulling image..."
docker-compose pull

echo "Building services..."
docker-compose build

echo "Preparing container..."
container=$(docker-compose run -d --rm test tail -f /dev/null)

if [[ $POST_MERGE_BUILD ]]; then
  # copy ssh and jira pem for host user
  docker cp ~/.ssh $container:/home/docker/.ssh
  docker exec -u 0 $container chown -R docker:docker /home/docker/.ssh

  docker cp .git $container:/usr/src/app/.git
  docker exec -u 0 $container chown -R docker:docker /usr/src/app/.git

  echo "Running release..."
  docker exec $container bash -c "yarn release"
else
  echo "Running tests..."
  docker exec $container bash -c "yarn test"
fi

docker stop $container
