#!/bin/bash

function cleanup() {
  exit_code=$?
  set +e

  echo "copying coverage reports..."
  docker cp $(docker-compose ps -q coverage):/usr/src/app/coverage .

  echo "cleaning up..."
  docker-compose stop test
  docker-compose rm -f test
  docker rmi -f $(docker images -qf "dangling=true") &>/dev/null

  exit $exit_code
}

trap cleanup INT TERM EXIT

set -e

export COMPOSE_FILE=./docker-compose.test.yml

echo "pull image..."
docker-compose pull

echo "building services..."
docker-compose build

echo "running tests..."
docker-compose run -u "root" --rm test bash -c "xvfb-daemon npm test"
