/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 - present Instructure, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import type { LucideProps } from 'lucide-react'
import type { ComponentStyle } from '@instructure/emotion'
import type { LucideIconTheme } from './theme'

/**
 * InstUI-specific props added to Lucide icons.
 *
 * These props provide InstUI-style API for icons, including semantic sizing,
 * theme-aware colors, rotation, RTL support, and accessibility features.
 */
export interface InstUIIconProps {
  /**
   * Size of the icon.
   * Can be a semantic size name (uses theme-based sizing) or a numeric pixel value.
   *
   * - Semantic sizes: 'x-small' (18px), 'small' (32px), 'medium' (48px), 'large' (80px), 'x-large' (160px)
   * - Numeric: Any number for pixel-based sizing (e.g., 24)
   */
  size?: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | number

  /**
   * Color of the icon.
   * Can be a semantic color name (uses theme colors) or any valid CSS color string.
   *
   * - Semantic colors: 'primary', 'secondary', 'success', 'error', 'warning', 'alert', 'brand'
   * - CSS colors: Any valid CSS color (e.g., '#ff0000', 'rgb(255, 0, 0)', 'currentColor')
   */
  color?:
    | 'inherit'
    | 'primary'
    | 'secondary'
    | 'primary-inverse'
    | 'secondary-inverse'
    | 'success'
    | 'error'
    | 'warning'
    | 'alert'
    | 'brand'
    | string

  /**
   * Rotation angle in degrees.
   * The icon will be rotated by the specified amount.
   */
  rotate?: '0' | '90' | '180' | '270'

  /**
   * Whether the icon should flip horizontally in RTL contexts.
   *
   * @default true
   *
   * When true (default), the icon automatically flips horizontally when the
   * document direction is RTL. Set to false to prevent flipping for icons
   * that should maintain their orientation in all contexts.
   */
  bidirectional?: boolean

  /**
   * Display mode for the icon.
   *
   * @default true
   *
   * - true: display as inline-block (flows with text)
   * - false: display as block (takes full width)
   */
  inline?: boolean

  /**
   * Accessible title for the icon.
   * If provided, the icon will have role="img" and proper aria-labelledby.
   */
  title?: string

  /**
   * Accessible description for the icon.
   * Used in combination with title for more detailed accessibility information.
   */
  description?: string

  /**
   * Ref forwarding for the underlying SVG element.
   * Alternative to the standard `ref` prop for compatibility with InstUI patterns.
   */
  elementRef?: React.Ref<SVGSVGElement>

  /**
   * Theme overrides for this specific icon instance.
   * Allows customization of theme variables on a per-component basis.
   */
  themeOverride?: Partial<LucideIconTheme>
}

/**
 * Combined props: InstUI + Lucide.
 *
 * This interface merges InstUI props with Lucide's native props, with InstUI
 * props taking precedence for `size`, `color`, and `rotate` (to support both semantic
 * and numeric/string values).
 */
export interface LucideIconWrapperProps
  extends Omit<LucideProps, 'size' | 'color' | 'rotate'>,
    InstUIIconProps {
  // size, color, and rotate are redefined in InstUIIconProps to support both formats:
  // - size: semantic ('small') OR numeric (24)
  // - color: semantic ('primary') OR CSS string ('#ff0000')
  // - rotate: semantic ('0', '90', '180', '270')
}

/**
 * Style object type for the icon wrapper.
 * Generated by the generateStyle function and consumed by the useStyle hook.
 */
export type LucideIconStyle = ComponentStyle<'lucideIcon'>

export { type LucideIconTheme }
