#!/bin/bash

set -ex

# Transpile ES6
babel -d __build__/lib lib

# Copy package
cp README.md __build__/
cp .npmignore __build__/
cp LICENSE __build__/
node -p 'p=require("./package");p.scripts=p.devDependencies=undefined;JSON.stringify(p,null,2)' > __build__/package.json

