#!/bin/bash -e

########################################
# Make sure working directory is clean #
########################################
if [ ! -z "$(git status --porcelain)" ]; then
  echo Refusing to operate on unclean working directory
  echo Use \"git status\" to see which files have been modified
  exit 1
fi

#########################
# Determine the version #
#########################
if [ $# -eq 0 ]
  then
    current_version=$(node -p "require('./package').version")
    printf "Next version (current is $current_version)? "
    read next_version # the npm version command should validate the version
else
  next_version="$@" # e.g. major, minor, patch
fi

if ! [[ $next_version ]]; then
  echo >&2 "A version is required."
  exit 1
fi

####################################
# npm version updates package.json #
####################################
npm --no-git-tag-version version $next_version

#####################################
# Commit the change to package.json #
#####################################
next_version=$(node -p "require('./package').version")
git commit -am "Version $next_version"
