#!/bin/bash

set -e

NPM_CLIENT=$(npm bin)/yarn

echo "Building and running tests..."
$NPM_CLIENT run test

if [[ $POST_MERGE_BUILD ]]; then
  echo "Running the release..."
  $NPM_CLIENT run release
fi
