#!/bin/bash

set -e

dotenv () {
  set -a
  [ -f .env ] && . .env
  set +a
}

dotenv

while getopts ":d:" opt; do
  case $opt in
    d)
      echo "-d (content directory): $OPTARG" >&2
      GH_PAGES_CONTENT=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

echo "Deploying $GH_PAGES_CONTENT to Github pages..."
echo "Repository: $GH_REPO..."

touch $GH_PAGES_CONTENT/.nojekyll

$(npm bin)/gh-pages -d "$GH_PAGES_CONTENT" -r "$GH_PAGES_REPO"
