#!/bin/bash -e

docs_path=__build__/docs

################
# Read options #
################
while getopts ":d:r:" opt; do
  case $opt in
    r)
      echo "-r (repo): $OPTARG" >&2
      repo=$OPTARG
      ;;
    d)
      echo "-d (docs directory path): $OPTARG" >&2
      docs_path=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if ! [[ $repo ]]; then
  echo >&2 "Repository is required (use option -r)."
  exit 1
fi

npm run build:docs

# https://github.com/github/pages-gem/pull/352
touch $docs_path/.nojekyll

gh-pages -d $docs_path -r $repo
