#!/bin/bash

set -e

######################################
# Determine the version to deprecate #
######################################
while getopts ":v:f:" opt; do
  case "$opt" in
    v)
      echo "-v (version): $OPTARG" >&2
      version="$OPTARG"
      ;;
    f)
      echo "-f (fix version): $OPTARG" >&2
      fix_version="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

message="A critical bug was fixed in ${fix_version}"
package="${LERNA_PACKAGE_NAME}@${version}"

echo "Deprecating ${package}..."
npm deprecate $package $message
