#!/bin/bash -e

build_path=__build__

npm install
npm test
npm run build

cp -R babel $build_path/babel

mkdir -p $build_path/webpack/loaders
cp webpack/loaders/themeable-css-loader.js $build_path/webpack/loaders

cp README.md $build_path/
cp .npmignore $build_path/
cp LICENSE $build_path/
