#!/bin/bash -e

echo '(╯°□°）╯︵ ┻━┻'

echo "-- install node"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm use

echo "-- clearing dependencies"
rm -rf node_modules
yarn cache clean

echo "-- installing dependencies"
yarn install
yarn bootstrap
