#!/bin/bash -e

NPM_CLIENT=$(npm bin)/yarn

echo '(╯°□°）╯︵ ┻━┻'

echo "-- install node"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm use

echo "-- clearing dependencies"
rm -rf node_modules
$NPM_CLIENT cache clean

echo "-- installing dependencies"
$NPM_CLIENT install
$NPM_CLIENT run bootstrap
