/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 - present Instructure, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * Generates versionedExports.ts from the version barrel files in @instructure/ui.
 * Run with: node --experimental-strip-types scripts/generateVersionedExports.ts
 * from the packages/ui-codemods directory.
 */

import { resolve } from 'node:path'
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import ts from 'typescript'

const VERSIONED_INSTUI = /^@instructure\/[^/]+\/v\d+_\d+$/

const uiSrcDir = resolve(import.meta.dirname, '../../ui/src')
const outputFile = resolve(
  import.meta.dirname,
  '../lib/generated/versionedExports.ts'
)

function parseVersionNumbers(filename: string): [number, number] {
  const m = filename.match(/^v(\d+)_(\d+)\.ts$/)
  return m ? [Number(m[1]), Number(m[2])] : [0, 0]
}

function findLatestVersionFile(dir: string): string {
  const latest = readdirSync(dir)
    .filter((f) => /^v\d+_\d+\.ts$/.test(f))
    .sort((a, b) => {
      const [amaj, amin] = parseVersionNumbers(a)
      const [bmaj, bmin] = parseVersionNumbers(b)
      return amaj - bmaj || amin - bmin
    })
    .at(-1)
  if (!latest) throw new Error(`No version files found in ${dir}`)
  return resolve(dir, latest)
}

function isVersionedInstUIExport(node: ts.ExportDeclaration): boolean {
  const { moduleSpecifier } = node
  return (
    moduleSpecifier !== undefined &&
    ts.isStringLiteral(moduleSpecifier) &&
    VERSIONED_INSTUI.test(moduleSpecifier.text)
  )
}

function getExportedNames(node: ts.ExportDeclaration): string[] {
  const { exportClause } = node
  if (!exportClause || !ts.isNamedExports(exportClause)) return []
  return exportClause.elements.map((el) => el.name.text)
}

function parseVersionedComponents(filePath: string): string[] {
  const source = readFileSync(filePath, 'utf-8')
  const sourceFile = ts.createSourceFile(
    filePath,
    source,
    ts.ScriptTarget.Latest
  )

  return sourceFile.statements
    .filter(ts.isExportDeclaration)
    .filter(isVersionedInstUIExport)
    .flatMap(getExportedNames)
}

function generateFileContent(components: string[]): string {
  const nameList = components.map((n) => `'${n}'`).join(', ')
  return `\
/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 - present Instructure, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Auto-generated by scripts/generateVersionedExports.ts — do not edit manually.
// Re-run the script when a new version barrel file is added to @instructure/ui.

const versionedExports: string[] = [${nameList}]

export default versionedExports
`
}

const filePath = findLatestVersionFile(uiSrcDir)
const components = parseVersionedComponents(filePath)

mkdirSync(resolve(outputFile, '..'), { recursive: true })
writeFileSync(outputFile, generateFileContent(components), 'utf-8')
process.stdout.write(`Written: ${outputFile}\n`)
