name: Cypress Component Tests
on: [pull_request]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Install Node 18
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap project
        run: npm run bootstrap
      - name: Run Cypress components tests
        run: npm run cy:component
