name: Deploy docs to gh-pages
on:
  push:
    branches:
      - master
      - v8_maintenance
      - v9_maintenance
      - v10_maintenance
  workflow_dispatch:
jobs:
  deploy-release:
    if: startsWith(github.event.head_commit.message, 'chore(release)')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci && npm run bootstrap
      - name: Set build directory and deployment path based on branch
        id: set-build-dir
        run: |
          echo "::set-output name=build_dir::./packages/__docs__/__build__"
          case "${{ github.ref }}" in
            "refs/heads/master")
              echo "::set-output name=deploy_dir::./"
              ;;
            "refs/heads/v8_maintenance")
              echo "::set-output name=deploy_dir::v8"
              ;;
            "refs/heads/v9_maintenance")
              echo "::set-output name=deploy_dir::v9"
              ;;
            "refs/heads/v10_maintenance")
              echo "::set-output name=deploy_dir::v10"
              ;;
          esac
      - name: Build docs-app
        run: npm run build:docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ steps.set-build-dir.outputs.build_dir }}
          branch: gh-pages
          target-folder: ${{ steps.set-build-dir.outputs.deploy_dir }}
          clean-exclude: |
            pr-preview
            v7
            v8
            v9
            v10
            latest
          force: false
  deploy-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Install Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci && npm run bootstrap
      - name: Build docs-app
        run: npm run build:docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/__docs__/__build__
          branch: gh-pages
          target-folder: latest
          force: false
