name: Docs deploy to Netlify
on:
  workflow_dispatch:
    inputs:
      docsVersion:
        description: 'Version of the Docs to release. Must be in format: vX eg.: v6 v7 ...'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install netlify-cli
        run: npm install --save-dev netlify-cli@13.2.2
      - name: Install packages.
        run: npm ci
      - name: Set up project.
        run: npm run bootstrap
      - name: Build docs-app.
        env:
          COPY_VERSIONS_JSON: 0
        run: npm run build:docs
      - name: Deploy docs-app to netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy --alias ${{ github.event.inputs.docsVersion }} --dir ./packages/__docs__/__build__
